[workspace]
members = [
  "crates/bitcoin",
  "crates/btc-relay",
  "crates/security",
  "crates/staked-relayers",
  "crates/exchange-rate-oracle",
  "crates/vault-registry",
  "crates/nomination",
  "crates/currency",
  "crates/issue",
  "crates/replace",
  "crates/redeem",
  "crates/sla",
  "crates/fee",
  "crates/refund",
  "crates/reward",
  "parachain",
  "parachain/runtime",
  "parachain/service",
  "parachain/rpc",
  "crates/parachain-info",
  "crates/parachain-tokens",
  "primitives",
]

resolver = "2"

[profile.test]
incremental = false
# debug = 0

[profile.dev]
incremental = false
# debug = 0