(function() {var implementors = {};
implementors["btc_relay"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"btc_relay/pallet/trait.Config.html\" title=\"trait btc_relay::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"btc_relay/pallet/struct.Pallet.html\" title=\"struct btc_relay::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["btc_relay::pallet::Pallet"]}];
implementors["exchange_rate_oracle"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"exchange_rate_oracle/pallet/trait.Config.html\" title=\"trait exchange_rate_oracle::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"exchange_rate_oracle/pallet/struct.Pallet.html\" title=\"struct exchange_rate_oracle::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["exchange_rate_oracle::pallet::Pallet"]}];
implementors["fee"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"fee/pallet/trait.Config.html\" title=\"trait fee::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"fee/pallet/struct.Pallet.html\" title=\"struct fee::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["fee::pallet::Pallet"]}];
implementors["issue"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"issue/pallet/trait.Config.html\" title=\"trait issue::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"issue/pallet/struct.Pallet.html\" title=\"struct issue::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["issue::pallet::Pallet"]}];
implementors["nomination"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"nomination/pallet/trait.Config.html\" title=\"trait nomination::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"nomination/pallet/struct.Pallet.html\" title=\"struct nomination::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["nomination::pallet::Pallet"]}];
implementors["parachain_info"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"parachain_info/pallet/trait.Config.html\" title=\"trait parachain_info::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"parachain_info/pallet/struct.Pallet.html\" title=\"struct parachain_info::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["parachain_info::pallet::Pallet"]}];
implementors["redeem"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"redeem/pallet/trait.Config.html\" title=\"trait redeem::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"redeem/pallet/struct.Pallet.html\" title=\"struct redeem::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["redeem::pallet::Pallet"]}];
implementors["refund"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"refund/pallet/trait.Config.html\" title=\"trait refund::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"refund/pallet/struct.Pallet.html\" title=\"struct refund::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["refund::pallet::Pallet"]}];
implementors["relay"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"relay/pallet/trait.Config.html\" title=\"trait relay::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"relay/pallet/struct.Pallet.html\" title=\"struct relay::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["relay::pallet::Pallet"]}];
implementors["replace"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"replace/pallet/trait.Config.html\" title=\"trait replace::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"replace/pallet/struct.Pallet.html\" title=\"struct replace::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["replace::pallet::Pallet"]}];
implementors["reward"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"reward/pallet/trait.Config.html\" title=\"trait reward::pallet::Config\">Config</a>&lt;I&gt;, I:&nbsp;'static&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"reward/pallet/struct.Pallet.html\" title=\"struct reward::pallet::Pallet\">Pallet</a>&lt;T, I&gt;","synthetic":false,"types":["reward::pallet::Pallet"]}];
implementors["security"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"security/pallet/trait.Config.html\" title=\"trait security::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"security/pallet/struct.Pallet.html\" title=\"struct security::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["security::pallet::Pallet"]}];
implementors["sla"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"sla/pallet/trait.Config.html\" title=\"trait sla::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"sla/pallet/struct.Pallet.html\" title=\"struct sla::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["sla::pallet::Pallet"]}];
implementors["staking"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"staking/pallet/trait.Config.html\" title=\"trait staking::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"staking/pallet/struct.Pallet.html\" title=\"struct staking::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["staking::pallet::Pallet"]}];
implementors["vault_registry"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"vault_registry/pallet/trait.Config.html\" title=\"trait vault_registry::pallet::Config\">Config</a>&gt; OnIdle&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"vault_registry/pallet/struct.Pallet.html\" title=\"struct vault_registry::pallet::Pallet\">Pallet</a>&lt;T&gt;","synthetic":false,"types":["vault_registry::pallet::Pallet"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()